apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: z12c1snqh-python 
  janus-idp.io/tekton: z12c1snqh-python
  backstage.io/kubernetes-id: z12c1snqh-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z12c1snqh-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  